apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-rt

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: bridge-rt-gateway
    newName: bridge-rt-gateway
    newTag: latest
  - name: bridge-rt-inference
    newName: bridge-rt-inference
    newTag: latest
