[package]
name = "gateway"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "gateway"

[dependencies]
opencv = "0.97"
thiserror = "2.0.17"
schema = { path = "../schema" }
bridge = { path = "../bridge" }
flatbuffers = "24.3"
anyhow = "1.0"
config = { version = "0.15.19", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
tracing = { version = "0.1.44", default-features = false }
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"]}
