[workspace]
resolver = "3"
members = ["crates/bridge","crates/common","crates/capture","crates/inference", "crates/logic", "crates/schema"]

[workspace.dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
