apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: detr-mmap
image: k3s-gpu:v1.31.5-k3s1
servers: 1
agents: 1  # Simulate edge device (e.g., Raspberry Pi)
ports:
  - port: 8080:30080
    nodeFilters:
      - loadbalancer
  - port: 9001:32001
    nodeFilters:
      - loadbalancer
  - port: 16686:30686
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ${PWD}/models:/models
    nodeFilters:
      - agent:0
  - volume: /dev:/dev
    nodeFilters:
      - agent:0
registries:
  create:
    name: k3d-registry
    host: "0.0.0.0"
    hostPort: "5000"
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - http://k3d-registry:5000
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  runtime:
    gpuRequest: "all"
