kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/jdelbar/Documents/projects/bridge-rt/models
        containerPath: /models
      - hostPath: /dev/video0
        containerPath: /dev/video0
