kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/jdelbar/Documents/projects/bridge-rt/models
        containerPath: /models
      - hostPath: /dev/video0
        containerPath: /dev/video0
      - hostPath: /dev/video1
        containerPath: /dev/video1
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
