apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - collector-configmap.yaml
  - collector-deployment.yaml
  - collector-service.yaml

patches:
  - path: inference-otel-patch.yaml
  - path: gateway-otel-patch.yaml
  - path: capture-otel-patch.yaml
  - path: controller-otel-patch.yaml
