apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: inference-patch.yaml

images:
  - name: bridge-rt-inference
    newName: localhost:5000/bridge-rt-inference-ort-cuda
    newTag: latest
