apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-rt

resources:
  - ../../base

components:
  - ../../components/k3d-dev

images:
  - name: bridge-rt-inference
    newName: localhost:5000/bridge-rt-inference
    newTag: latest
