apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: inference-patch.yaml

images:
  - name: detr-mmap-inference
    newName: localhost:5000/detr-mmap-inference-trt
    newTag: latest
