apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: detr-mmap

resources:
  - ../../base

components:
  - ../../components/k3d-dev
  - ../../components/inference-trt
  - ../../components/otel-collector
