apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-rt

resources:
  - ../../base

patches:
  - path: capture-patch.yaml
  - path: inference-patch.yaml
  - path: gateway-patch.yaml

images:
  - name: bridge-rt-capture
    newName: localhost:5000/bridge-rt-capture
    newTag: latest
  - name: bridge-rt-controller
    newName: localhost:5000/bridge-rt-controller
    newTag: latest
  - name: bridge-rt-inference
    newName: localhost:5000/bridge-rt-inference
    newTag: latest
  - name: bridge-rt-gateway
    newName: localhost:5000/bridge-rt-gateway
    newTag: latest
