apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-rt

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml

images:
  - name: bridge-rt-capture
    newName: localhost:5000/bridge-rt-capture
    newTag: latest
  - name: bridge-rt-inference
    newName: localhost:5000/bridge-rt-inference
    newTag: latest
  - name: bridge-rt-logic
    newName: localhost:5000/bridge-rt-logic
    newTag: latest
