apiVersion: v1
kind: Service
metadata:
  name: bridge-rt-service
  labels:
    app: bridge-rt
    component: gateway
spec:
  type: NodePort
  selector:
    app: bridge-rt
    component: gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: websocket
