apiVersion: v1
kind: Service
metadata:
  name: detr-mmap-service
  labels:
    app: detr-mmap
    component: gateway
spec:
  type: NodePort
  selector:
    app: detr-mmap
    component: gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: websocket
