apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-rt

resources:
  - namespace.yaml
  - capture-deployment.yaml
  - inference-deployment.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml

labels:
  - pairs:
      project: bridge-rt
      managed-by: kustomize
