apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: detr-mmap

resources:
  - namespace.yaml
  - capture-deployment.yaml
  - controller-deployment.yaml
  - inference-deployment.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - mosquitto-configmap.yaml
  - mosquitto-statefulset.yaml
  - mosquitto-service.yaml

labels:
  - pairs:
      project: detr-mmap
      managed-by: kustomize
