apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: bridge-rt
    component: mosquitto
spec:
  type: ClusterIP
  selector:
    app: bridge-rt
    component: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-external
  labels:
    app: bridge-rt
    component: mosquitto
spec:
  type: NodePort
  selector:
    app: bridge-rt
    component: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      nodePort: 31883
      protocol: TCP
      name: mqtt
