apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: capture-patch.yaml
  - path: controller-patch.yaml
  - path: inference-patch.yaml
  - path: gateway-patch.yaml

images:
  - name: detr-mmap-capture
    newName: localhost:5000/detr-mmap-capture
    newTag: latest
  - name: detr-mmap-controller
    newName: localhost:5000/detr-mmap-controller
    newTag: latest
  - name: detr-mmap-gateway
    newName: localhost:5000/detr-mmap-gateway
    newTag: latest
